site_name: MicroSim Search and Embeddings
site_description: 'MicroSim Faceted Search CC ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/search-microsims/'
repo_url: 'https://github.com/dmccreary/search-microsims'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - Search Demo: search/index.md
  - MicroSim Schema: microsim-schema.md
  - MicroSim Embeddings: microsim-embeddings.md
  - Reports:
      - MicroSim Metrics: reports/microsim-metrics.md
      - Local Metadata Update: reports/local-metadata-update.md
      - MicroSim PCA Map: sims/pca-map/index.md
  
  - MicroSims:
    - List of MicroSims: sims/index.md
    - Search Workflow: sims/search-workflow/index.md
    - Similar MicroSims: sims/list-similar-microsim/index.md
    - PCA Map: sims/pca-map/index.md
    - Learing Graph Viewer: sims/graph-viewer/index.md
  
  - Prompts:
      - Add Missing Metadata: prompts/add-missing-metadata.md
      - Create Embeddings Report: prompts/create-embeddings-report.md
  - Learning Graph:
      - Introduction: learning-graph/index.md
      - Graph Viewer: sims/graph-viewer/index.md
      - Course Description Assessment: learning-graph/course-description-assessment.md
      - Concept List: learning-graph/concept-list.md
      - Concept Taxonomy: learning-graph/concept-taxonomy.md
      - Quality Metrics: learning-graph/quality-metrics.md
      - Taxonomy Distribution: learning-graph/taxonomy-distribution.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - License: license.md
  - Contact: contact.md
 
theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX